export interface Country {
  code: string;
  name: string;
  dialCode: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", dialCode: "+93", flag: "\u{1F1E6}\u{1F1EB}" },
  { code: "AL", name: "Albania", dialCode: "+355", flag: "\u{1F1E6}\u{1F1F1}" },
  { code: "DZ", name: "Algeria", dialCode: "+213", flag: "\u{1F1E9}\u{1F1FF}" },
  { code: "AO", name: "Angola", dialCode: "+244", flag: "\u{1F1E6}\u{1F1F4}" },
  { code: "AR", name: "Argentina", dialCode: "+54", flag: "\u{1F1E6}\u{1F1F7}" },
  { code: "AU", name: "Australia", dialCode: "+61", flag: "\u{1F1E6}\u{1F1FA}" },
  { code: "AT", name: "Austria", dialCode: "+43", flag: "\u{1F1E6}\u{1F1F9}" },
  { code: "BH", name: "Bahrain", dialCode: "+973", flag: "\u{1F1E7}\u{1F1ED}" },
  { code: "BD", name: "Bangladesh", dialCode: "+880", flag: "\u{1F1E7}\u{1F1E9}" },
  { code: "BE", name: "Belgium", dialCode: "+32", flag: "\u{1F1E7}\u{1F1EA}" },
  { code: "BJ", name: "Benin", dialCode: "+229", flag: "\u{1F1E7}\u{1F1EF}" },
  { code: "BW", name: "Botswana", dialCode: "+267", flag: "\u{1F1E7}\u{1F1FC}" },
  { code: "BR", name: "Brazil", dialCode: "+55", flag: "\u{1F1E7}\u{1F1F7}" },
  { code: "BF", name: "Burkina Faso", dialCode: "+226", flag: "\u{1F1E7}\u{1F1EB}" },
  { code: "BI", name: "Burundi", dialCode: "+257", flag: "\u{1F1E7}\u{1F1EE}" },
  { code: "CM", name: "Cameroon", dialCode: "+237", flag: "\u{1F1E8}\u{1F1F2}" },
  { code: "CA", name: "Canada", dialCode: "+1", flag: "\u{1F1E8}\u{1F1E6}" },
  { code: "CF", name: "Central African Republic", dialCode: "+236", flag: "\u{1F1E8}\u{1F1EB}" },
  { code: "TD", name: "Chad", dialCode: "+235", flag: "\u{1F1F9}\u{1F1E9}" },
  { code: "CL", name: "Chile", dialCode: "+56", flag: "\u{1F1E8}\u{1F1F1}" },
  { code: "CN", name: "China", dialCode: "+86", flag: "\u{1F1E8}\u{1F1F3}" },
  { code: "CO", name: "Colombia", dialCode: "+57", flag: "\u{1F1E8}\u{1F1F4}" },
  { code: "CG", name: "Congo", dialCode: "+242", flag: "\u{1F1E8}\u{1F1EC}" },
  { code: "CD", name: "Congo (DRC)", dialCode: "+243", flag: "\u{1F1E8}\u{1F1E9}" },
  { code: "CI", name: "C\u00f4te d'Ivoire", dialCode: "+225", flag: "\u{1F1E8}\u{1F1EE}" },
  { code: "HR", name: "Croatia", dialCode: "+385", flag: "\u{1F1ED}\u{1F1F7}" },
  { code: "CU", name: "Cuba", dialCode: "+53", flag: "\u{1F1E8}\u{1F1FA}" },
  { code: "CZ", name: "Czech Republic", dialCode: "+420", flag: "\u{1F1E8}\u{1F1FF}" },
  { code: "DK", name: "Denmark", dialCode: "+45", flag: "\u{1F1E9}\u{1F1F0}" },
  { code: "EG", name: "Egypt", dialCode: "+20", flag: "\u{1F1EA}\u{1F1EC}" },
  { code: "ER", name: "Eritrea", dialCode: "+291", flag: "\u{1F1EA}\u{1F1F7}" },
  { code: "ET", name: "Ethiopia", dialCode: "+251", flag: "\u{1F1EA}\u{1F1F9}" },
  { code: "FI", name: "Finland", dialCode: "+358", flag: "\u{1F1EB}\u{1F1EE}" },
  { code: "FR", name: "France", dialCode: "+33", flag: "\u{1F1EB}\u{1F1F7}" },
  { code: "GA", name: "Gabon", dialCode: "+241", flag: "\u{1F1EC}\u{1F1E6}" },
  { code: "DE", name: "Germany", dialCode: "+49", flag: "\u{1F1E9}\u{1F1EA}" },
  { code: "GH", name: "Ghana", dialCode: "+233", flag: "\u{1F1EC}\u{1F1ED}" },
  { code: "GR", name: "Greece", dialCode: "+30", flag: "\u{1F1EC}\u{1F1F7}" },
  { code: "GN", name: "Guinea", dialCode: "+224", flag: "\u{1F1EC}\u{1F1F3}" },
  { code: "HK", name: "Hong Kong", dialCode: "+852", flag: "\u{1F1ED}\u{1F1F0}" },
  { code: "HU", name: "Hungary", dialCode: "+36", flag: "\u{1F1ED}\u{1F1FA}" },
  { code: "IN", name: "India", dialCode: "+91", flag: "\u{1F1EE}\u{1F1F3}" },
  { code: "ID", name: "Indonesia", dialCode: "+62", flag: "\u{1F1EE}\u{1F1E9}" },
  { code: "IR", name: "Iran", dialCode: "+98", flag: "\u{1F1EE}\u{1F1F7}" },
  { code: "IQ", name: "Iraq", dialCode: "+964", flag: "\u{1F1EE}\u{1F1F6}" },
  { code: "IE", name: "Ireland", dialCode: "+353", flag: "\u{1F1EE}\u{1F1EA}" },
  { code: "IL", name: "Israel", dialCode: "+972", flag: "\u{1F1EE}\u{1F1F1}" },
  { code: "IT", name: "Italy", dialCode: "+39", flag: "\u{1F1EE}\u{1F1F9}" },
  { code: "JM", name: "Jamaica", dialCode: "+1876", flag: "\u{1F1EF}\u{1F1F2}" },
  { code: "JP", name: "Japan", dialCode: "+81", flag: "\u{1F1EF}\u{1F1F5}" },
  { code: "JO", name: "Jordan", dialCode: "+962", flag: "\u{1F1EF}\u{1F1F4}" },
  { code: "KE", name: "Kenya", dialCode: "+254", flag: "\u{1F1F0}\u{1F1EA}" },
  { code: "KR", name: "South Korea", dialCode: "+82", flag: "\u{1F1F0}\u{1F1F7}" },
  { code: "KW", name: "Kuwait", dialCode: "+965", flag: "\u{1F1F0}\u{1F1FC}" },
  { code: "LS", name: "Lesotho", dialCode: "+266", flag: "\u{1F1F1}\u{1F1F8}" },
  { code: "LR", name: "Liberia", dialCode: "+231", flag: "\u{1F1F1}\u{1F1F7}" },
  { code: "MG", name: "Madagascar", dialCode: "+261", flag: "\u{1F1F2}\u{1F1EC}" },
  { code: "MW", name: "Malawi", dialCode: "+265", flag: "\u{1F1F2}\u{1F1FC}" },
  { code: "MY", name: "Malaysia", dialCode: "+60", flag: "\u{1F1F2}\u{1F1FE}" },
  { code: "ML", name: "Mali", dialCode: "+223", flag: "\u{1F1F2}\u{1F1F1}" },
  { code: "MX", name: "Mexico", dialCode: "+52", flag: "\u{1F1F2}\u{1F1FD}" },
  { code: "MA", name: "Morocco", dialCode: "+212", flag: "\u{1F1F2}\u{1F1E6}" },
  { code: "MZ", name: "Mozambique", dialCode: "+258", flag: "\u{1F1F2}\u{1F1FF}" },
  { code: "NA", name: "Namibia", dialCode: "+264", flag: "\u{1F1F3}\u{1F1E6}" },
  { code: "NL", name: "Netherlands", dialCode: "+31", flag: "\u{1F1F3}\u{1F1F1}" },
  { code: "NZ", name: "New Zealand", dialCode: "+64", flag: "\u{1F1F3}\u{1F1FF}" },
  { code: "NE", name: "Niger", dialCode: "+227", flag: "\u{1F1F3}\u{1F1EA}" },
  { code: "NG", name: "Nigeria", dialCode: "+234", flag: "\u{1F1F3}\u{1F1EC}" },
  { code: "NO", name: "Norway", dialCode: "+47", flag: "\u{1F1F3}\u{1F1F4}" },
  { code: "OM", name: "Oman", dialCode: "+968", flag: "\u{1F1F4}\u{1F1F2}" },
  { code: "PK", name: "Pakistan", dialCode: "+92", flag: "\u{1F1F5}\u{1F1F0}" },
  { code: "PH", name: "Philippines", dialCode: "+63", flag: "\u{1F1F5}\u{1F1ED}" },
  { code: "PL", name: "Poland", dialCode: "+48", flag: "\u{1F1F5}\u{1F1F1}" },
  { code: "PT", name: "Portugal", dialCode: "+351", flag: "\u{1F1F5}\u{1F1F9}" },
  { code: "QA", name: "Qatar", dialCode: "+974", flag: "\u{1F1F6}\u{1F1E6}" },
  { code: "RO", name: "Romania", dialCode: "+40", flag: "\u{1F1F7}\u{1F1F4}" },
  { code: "RU", name: "Russia", dialCode: "+7", flag: "\u{1F1F7}\u{1F1FA}" },
  { code: "RW", name: "Rwanda", dialCode: "+250", flag: "\u{1F1F7}\u{1F1FC}" },
  { code: "SA", name: "Saudi Arabia", dialCode: "+966", flag: "\u{1F1F8}\u{1F1E6}" },
  { code: "SN", name: "Senegal", dialCode: "+221", flag: "\u{1F1F8}\u{1F1F3}" },
  { code: "SG", name: "Singapore", dialCode: "+65", flag: "\u{1F1F8}\u{1F1EC}" },
  { code: "ZA", name: "South Africa", dialCode: "+27", flag: "\u{1F1FF}\u{1F1E6}" },
  { code: "ES", name: "Spain", dialCode: "+34", flag: "\u{1F1EA}\u{1F1F8}" },
  { code: "SD", name: "Sudan", dialCode: "+249", flag: "\u{1F1F8}\u{1F1E9}" },
  { code: "SZ", name: "Eswatini", dialCode: "+268", flag: "\u{1F1F8}\u{1F1FF}" },
  { code: "SE", name: "Sweden", dialCode: "+46", flag: "\u{1F1F8}\u{1F1EA}" },
  { code: "CH", name: "Switzerland", dialCode: "+41", flag: "\u{1F1E8}\u{1F1ED}" },
  { code: "TZ", name: "Tanzania", dialCode: "+255", flag: "\u{1F1F9}\u{1F1FF}" },
  { code: "TH", name: "Thailand", dialCode: "+66", flag: "\u{1F1F9}\u{1F1ED}" },
  { code: "TG", name: "Togo", dialCode: "+228", flag: "\u{1F1F9}\u{1F1EC}" },
  { code: "TN", name: "Tunisia", dialCode: "+216", flag: "\u{1F1F9}\u{1F1F3}" },
  { code: "TR", name: "Turkey", dialCode: "+90", flag: "\u{1F1F9}\u{1F1F7}" },
  { code: "UG", name: "Uganda", dialCode: "+256", flag: "\u{1F1FA}\u{1F1EC}" },
  { code: "UA", name: "Ukraine", dialCode: "+380", flag: "\u{1F1FA}\u{1F1E6}" },
  { code: "AE", name: "United Arab Emirates", dialCode: "+971", flag: "\u{1F1E6}\u{1F1EA}" },
  { code: "GB", name: "United Kingdom", dialCode: "+44", flag: "\u{1F1EC}\u{1F1E7}" },
  { code: "US", name: "United States", dialCode: "+1", flag: "\u{1F1FA}\u{1F1F8}" },
  { code: "VN", name: "Vietnam", dialCode: "+84", flag: "\u{1F1FB}\u{1F1F3}" },
  { code: "ZM", name: "Zambia", dialCode: "+260", flag: "\u{1F1FF}\u{1F1F2}" },
  { code: "ZW", name: "Zimbabwe", dialCode: "+263", flag: "\u{1F1FF}\u{1F1FC}" },
];

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code);
}

export function getDialCodeByCountry(code: string): string {
  return getCountryByCode(code)?.dialCode ?? "";
}
