export const ErrorCode = {
  // Auth
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // Resources
  NOT_FOUND: "NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  CONFLICT: "CONFLICT",

  // Reservations
  ROOM_UNAVAILABLE: "ROOM_UNAVAILABLE",
  INVALID_DATES: "INVALID_DATES",
  RESERVATION_NOT_CONFIRMED: "RESERVATION_NOT_CONFIRMED",
  RESERVATION_NOT_CHECKED_IN: "RESERVATION_NOT_CHECKED_IN",
  FOLIO_NOT_SETTLED: "FOLIO_NOT_SETTLED",

  // System
  INTERNAL_ERROR: "INTERNAL_ERROR",
  RATE_LIMITED: "RATE_LIMITED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
